version: '3.7'

services:
  app:
    image: pokill:dev
    container_name: pokill_app
    build:
      context: .
      dockerfile: Dockerfile.pokill_dev
      args:
        - USER_ID
        - GROUP_ID
        - USERNAME
        - USERGROUP
        - HOMEDIR
    deploy:
      resources:
        limits:
          memory: 1024m
    environment:
      - BASE64_ENCODE
      - REFRESH_TOKEN
      - POKILL_DEV_USERNAME
      - POKILL_DEV_PASSWORD
      - POKILL_DEV_DBNAME
      - POKILL_DEV_HOST
      - EVE_DEV_USERNAME
      - EVE_DEV_PASSWORD
      - EVE_DEV_DBNAME
      - EVE_DEV_HOST
      - USER_ID
      - GROUP_ID
      - USERNAME
      - USERGROUP
      - HOMEDIR
    command: bash -c "rails db:migrate && bundle exec puma -C config/puma.rb"
    volumes:
      - ./pokill:/pokill
      - tmp_data:/pokill/tmp/sockets
    depends_on:
      - pg_db
      - mysql_db

  cron:
    image: cron:dev
    container_name: cron
    build:
      context: .
      dockerfile: Dockerfile.cron
    deploy:
      resources:
        limits: 
          memory: 128m
    depends_on:
      - app 
    command: crond -f -l 8 -L /var/log/pokill/cron.log
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/log/pokill:/var/log/pokill
      - ./cron_tasks/1min:/etc/periodic/1min/:ro
      - ./cron_tasks/15min:/etc/periodic/15min/:ro
      - ./cron_tasks/weekly:/etc/periodic/weekly/:ro

  nginx_proxy:
    image: nginx:dev 
    container_name: nginx_proxy
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
    deploy:
      resources:
        limits:
          memory: 128m
    depends_on:
      - app
    volumes:
      - tmp_data:/pokill/tmp/sockets

  pg_db:
    image: postgres:dev
    container_name: postgres
    build:
      context: .
      dockerfile: Dockerfile.pg
    ports:
      - 5432
    deploy:
      resources:
        limits:
          memory: 256m
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    volumes:
      - pg_data:/var/lib/postgresql/data

  mysql_db:
    image: mysql:dev
    container_name: mysql
    build:
      context: .
      dockerfile: Dockerfile.mysql
    deploy:
      resources:
        limits:
          memory: 128m
    environment:
      - MYSQL_DATABASE
      - MYSQL_ROOT_PASSWORD
      - MYSQL_USER
      - MYSQL_PASSWORD
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  pg_data:
  mysql_data:
  tmp_data:
