#!/bin/sh
docker build -t pokill-dev --build-arg USER_ID=$(id -u) --build-arg GROUP_ID=$(id -g) --build-arg USERNAME="nath_dev" --build-arg HOMEDIR="/home/nath_dev" --build-arg USERGROUP="nath_dev" --network host -f Dockerfile.pokill .
