#!/bin/sh
LOG="/var/log/pokill/cron.log"
echo "`date -Iseconds`: running rake task eve_import:killmails on pokill app container" >> $LOG 2>&1
docker exec pokill_app bin/rake eve_import:killmails >> $LOG 2>&1
echo "`date -Iseconds`: completed rake task eve_import:killmails on pokill app container" >> $LOG 2>&1
echo "`date -Iseconds`: running rake task eve_import:characters on pokill app container" >> $LOG 2>&1
docker exec pokill_app bin/rake eve_import:characters >> $LOG 2>&1
echo "`date -Iseconds`: completed rake task eve_import:characters on pokill app container" >> $LOG 2>&1
echo "`date -Iseconds`: running rake task eve_import:corporations on pokill app container" >> $LOG 2>&1
docker exec pokill_app bin/rake eve_import:corporations >> $LOG 2>&1
echo "`date -Iseconds`: completed rake task eve_import:corporations on pokill app container" >> $LOG 2>&1
echo "`date -Iseconds`: running rake task eve_import:alliances on pokill app container" >> $LOG 2>&1
docker exec pokill_app bin/rake eve_import:alli >> $LOG 2>&1
echo "`date -Iseconds`: completed rake task eve_import:alliances on pokill app container" >> $LOG 2>&1
